# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\TestPyQt5\fault_diagnosis\Main_Ui_Fault_Diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1316, 705)
        MainWindow.setStyleSheet("    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    selection-background-color:#3daee9;\n"
"    selection-color: #eff0f1;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    outline: 0;")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background: rgb(68, 68, 68);\n"
"color: rgb(220, 220, 220);")
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(59, 14, 1241, 662))
        self.tabWidget.setStyleSheet("QTabWidget::pane { \n"
"border: 1.5px solid rgb(36, 36, 36); \n"
"}    \n"
"\n"
"QTabWidget {\n"
"        border: 1px solid rgb(36, 36, 36);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"        color:rgb(220, 220, 220);\n"
"        background: rgb(100, 100, 100);\n"
"        min-width:100px;\n"
"        min-height:25px;\n"
"        border: 1px solid rgb(36, 36, 36); \n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(1, 3, 737, 622))
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}\n"
"\n"
"")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.groupBox_7)
        self.tabWidget_2.setGeometry(QtCore.QRect(234, 3, 236, 58))
        self.tabWidget_2.setStyleSheet("QTabBar::tab {\n"
"min-width:80px;\n"
"min-height:20px;\n"
"}    \n"
"QTabBar::tab {\n"
"        color:rgb(220, 220, 220);\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(82, 82, 82);\n"
"}")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(5, 5, 222, 25))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setIconSize(QtCore.QSize(20, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.pushButton_Suspend = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Suspend.setGeometry(QtCore.QRect(418, 568, 102, 44))
        self.pushButton_Suspend.setMinimumSize(QtCore.QSize(102, 44))
        self.pushButton_Suspend.setMaximumSize(QtCore.QSize(102, 44))
        self.pushButton_Suspend.setStyleSheet("QPushButton:enabled {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(56, 56, 56);\n"
"}")
        self.pushButton_Suspend.setObjectName("pushButton_Suspend")
        self.pushButton_Run = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Run.setGeometry(QtCore.QRect(185, 568, 102, 44))
        self.pushButton_Run.setMinimumSize(QtCore.QSize(102, 44))
        self.pushButton_Run.setMaximumSize(QtCore.QSize(102, 44))
        self.pushButton_Run.setStyleSheet("\n"
"QPushButton:enabled {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(56, 56, 56);\n"
"}\n"
"")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Stop.setGeometry(QtCore.QRect(301, 567, 102, 44))
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(102, 44))
        self.pushButton_Stop.setMaximumSize(QtCore.QSize(102, 44))
        self.pushButton_Stop.setStyleSheet("QPushButton:enabled {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(56, 56, 56);\n"
"}")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit.setGeometry(QtCore.QRect(234, 130, 236, 409))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_Add_Cmd = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Add_Cmd.setGeometry(QtCore.QRect(232, 77, 102, 44))
        self.pushButton_Add_Cmd.setMinimumSize(QtCore.QSize(102, 44))
        self.pushButton_Add_Cmd.setMaximumSize(QtCore.QSize(102, 44))
        self.pushButton_Add_Cmd.setStyleSheet("QPushButton:enabled {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(56, 56, 56);\n"
"}\n"
"")
        self.pushButton_Add_Cmd.setObjectName("pushButton_Add_Cmd")
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_Clear.setGeometry(QtCore.QRect(369, 77, 102, 44))
        self.pushButton_Clear.setMinimumSize(QtCore.QSize(102, 44))
        self.pushButton_Clear.setMaximumSize(QtCore.QSize(102, 44))
        self.pushButton_Clear.setStyleSheet("QPushButton:enabled {\n"
"        background: rgb(82, 82, 82);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(56, 56, 56);\n"
"}\n"
"")
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.toolBox = QtWidgets.QToolBox(self.tab)
        self.toolBox.setGeometry(QtCore.QRect(774, 1, 460, 537))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 460, 485))
        self.page.setObjectName("page")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 80, 459, 218))
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}\n"
"\n"
"\n"
"")
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_58 = QtWidgets.QLabel(self.groupBox_6)
        self.label_58.setGeometry(QtCore.QRect(14, 108, 48, 16))
        self.label_58.setObjectName("label_58")
        self.label_52 = QtWidgets.QLabel(self.groupBox_6)
        self.label_52.setGeometry(QtCore.QRect(172, 50, 48, 16))
        self.label_52.setObjectName("label_52")
        self.label_56 = QtWidgets.QLabel(self.groupBox_6)
        self.label_56.setGeometry(QtCore.QRect(322, 106, 48, 16))
        self.label_56.setObjectName("label_56")
        self.label_48 = QtWidgets.QLabel(self.groupBox_6)
        self.label_48.setGeometry(QtCore.QRect(5, 50, 59, 16))
        self.label_48.setObjectName("label_48")
        self.label_201 = QtWidgets.QLabel(self.groupBox_6)
        self.label_201.setGeometry(QtCore.QRect(322, 136, 50, 16))
        self.label_201.setObjectName("label_201")
        self.label_96 = QtWidgets.QLabel(self.groupBox_6)
        self.label_96.setGeometry(QtCore.QRect(14, 164, 49, 16))
        self.label_96.setObjectName("label_96")
        self.label_47 = QtWidgets.QLabel(self.groupBox_6)
        self.label_47.setGeometry(QtCore.QRect(5, 20, 60, 16))
        self.label_47.setObjectName("label_47")
        self.label_51 = QtWidgets.QLabel(self.groupBox_6)
        self.label_51.setGeometry(QtCore.QRect(172, 20, 48, 16))
        self.label_51.setObjectName("label_51")
        self.label_55 = QtWidgets.QLabel(self.groupBox_6)
        self.label_55.setGeometry(QtCore.QRect(322, 21, 48, 16))
        self.label_55.setObjectName("label_55")
        self.label_57 = QtWidgets.QLabel(self.groupBox_6)
        self.label_57.setGeometry(QtCore.QRect(322, 50, 48, 16))
        self.label_57.setObjectName("label_57")
        self.label_95 = QtWidgets.QLabel(self.groupBox_6)
        self.label_95.setGeometry(QtCore.QRect(14, 136, 49, 16))
        self.label_95.setObjectName("label_95")
        self.label_198 = QtWidgets.QLabel(self.groupBox_6)
        self.label_198.setGeometry(QtCore.QRect(322, 164, 48, 16))
        self.label_198.setObjectName("label_198")
        self.label_200 = QtWidgets.QLabel(self.groupBox_6)
        self.label_200.setGeometry(QtCore.QRect(322, 190, 48, 16))
        self.label_200.setObjectName("label_200")
        self.label_49 = QtWidgets.QLabel(self.groupBox_6)
        self.label_49.setGeometry(QtCore.QRect(5, 80, 60, 16))
        self.label_49.setObjectName("label_49")
        self.label_53 = QtWidgets.QLabel(self.groupBox_6)
        self.label_53.setGeometry(QtCore.QRect(161, 80, 60, 16))
        self.label_53.setObjectName("label_53")
        self.label_59 = QtWidgets.QLabel(self.groupBox_6)
        self.label_59.setGeometry(QtCore.QRect(312, 80, 63, 16))
        self.label_59.setObjectName("label_59")
        self.label_61 = QtWidgets.QLabel(self.groupBox_6)
        self.label_61.setGeometry(QtCore.QRect(160, 110, 64, 16))
        self.label_61.setObjectName("label_61")
        self.label_202 = QtWidgets.QLabel(self.groupBox_6)
        self.label_202.setGeometry(QtCore.QRect(172, 164, 48, 16))
        self.label_202.setObjectName("label_202")
        self.label_203 = QtWidgets.QLabel(self.groupBox_6)
        self.label_203.setGeometry(QtCore.QRect(172, 136, 48, 16))
        self.label_203.setObjectName("label_203")
        self.label_204 = QtWidgets.QLabel(self.groupBox_6)
        self.label_204.setGeometry(QtCore.QRect(172, 190, 48, 16))
        self.label_204.setObjectName("label_204")
        self.labelEdit_DSP_X = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_DSP_X.setGeometry(QtCore.QRect(66, 18, 80, 22))
        self.labelEdit_DSP_X.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DSP_X.setText("")
        self.labelEdit_DSP_X.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DSP_X.setObjectName("labelEdit_DSP_X")
        self.labelEdit_DSP_Y = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_DSP_Y.setGeometry(QtCore.QRect(66, 48, 80, 22))
        self.labelEdit_DSP_Y.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DSP_Y.setText("")
        self.labelEdit_DSP_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DSP_Y.setObjectName("labelEdit_DSP_Y")
        self.labelEdit_DSP_H = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_DSP_H.setGeometry(QtCore.QRect(222, 18, 80, 22))
        self.labelEdit_DSP_H.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DSP_H.setText("")
        self.labelEdit_DSP_H.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DSP_H.setObjectName("labelEdit_DSP_H")
        self.labelEdit_AgvSpeed = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_AgvSpeed.setGeometry(QtCore.QRect(222, 48, 80, 22))
        self.labelEdit_AgvSpeed.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_AgvSpeed.setText("")
        self.labelEdit_AgvSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_AgvSpeed.setObjectName("labelEdit_AgvSpeed")
        self.labelEdit_ElectricQuantity = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_ElectricQuantity.setGeometry(QtCore.QRect(66, 162, 80, 22))
        self.labelEdit_ElectricQuantity.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_ElectricQuantity.setText("")
        self.labelEdit_ElectricQuantity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_ElectricQuantity.setObjectName("labelEdit_ElectricQuantity")
        self.labelEdit_PodaAngle = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_PodaAngle.setGeometry(QtCore.QRect(374, 18, 80, 22))
        self.labelEdit_PodaAngle.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_PodaAngle.setText("")
        self.labelEdit_PodaAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_PodaAngle.setObjectName("labelEdit_PodaAngle")
        self.labelEdit_PodHeight = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_PodHeight.setGeometry(QtCore.QRect(374, 48, 80, 22))
        self.labelEdit_PodHeight.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_PodHeight.setText("")
        self.labelEdit_PodHeight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_PodHeight.setObjectName("labelEdit_PodHeight")
        self.labelEdit_BarrierAngle = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_BarrierAngle.setGeometry(QtCore.QRect(66, 106, 80, 22))
        self.labelEdit_BarrierAngle.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_BarrierAngle.setText("")
        self.labelEdit_BarrierAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_BarrierAngle.setObjectName("labelEdit_BarrierAngle")
        self.labelEdit_PresentInstruction = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_PresentInstruction.setGeometry(QtCore.QRect(374, 134, 80, 22))
        self.labelEdit_PresentInstruction.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_PresentInstruction.setText("")
        self.labelEdit_PresentInstruction.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_PresentInstruction.setObjectName("labelEdit_PresentInstruction")
        self.labelEdit_BarrierDistance = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_BarrierDistance.setGeometry(QtCore.QRect(374, 106, 80, 22))
        self.labelEdit_BarrierDistance.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_BarrierDistance.setText("")
        self.labelEdit_BarrierDistance.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_BarrierDistance.setObjectName("labelEdit_BarrierDistance")
        self.labelEdit_battery_voltage = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_battery_voltage.setGeometry(QtCore.QRect(66, 134, 80, 22))
        self.labelEdit_battery_voltage.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_battery_voltage.setText("")
        self.labelEdit_battery_voltage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_battery_voltage.setObjectName("labelEdit_battery_voltage")
        self.labelEdit_LeftLoadRate = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_LeftLoadRate.setGeometry(QtCore.QRect(66, 78, 80, 22))
        self.labelEdit_LeftLoadRate.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LeftLoadRate.setText("")
        self.labelEdit_LeftLoadRate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LeftLoadRate.setObjectName("labelEdit_LeftLoadRate")
        self.labelEdit_RightLoadRate = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_RightLoadRate.setGeometry(QtCore.QRect(222, 78, 80, 22))
        self.labelEdit_RightLoadRate.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_RightLoadRate.setText("")
        self.labelEdit_RightLoadRate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_RightLoadRate.setObjectName("labelEdit_RightLoadRate")
        self.labelEdit_LiftupLoadRate = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_LiftupLoadRate.setGeometry(QtCore.QRect(374, 78, 80, 22))
        self.labelEdit_LiftupLoadRate.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LiftupLoadRate.setText("")
        self.labelEdit_LiftupLoadRate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LiftupLoadRate.setObjectName("labelEdit_LiftupLoadRate")
        self.labelEdit_LeftRightLoadRate = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_LeftRightLoadRate.setGeometry(QtCore.QRect(222, 106, 80, 22))
        self.labelEdit_LeftRightLoadRate.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LeftRightLoadRate.setText("")
        self.labelEdit_LeftRightLoadRate.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LeftRightLoadRate.setObjectName("labelEdit_LeftRightLoadRate")
        self.labelEdit_LeftCurrent = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_LeftCurrent.setGeometry(QtCore.QRect(222, 162, 80, 22))
        self.labelEdit_LeftCurrent.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LeftCurrent.setText("")
        self.labelEdit_LeftCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LeftCurrent.setObjectName("labelEdit_LeftCurrent")
        self.labelEdit_RightCurrent = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_RightCurrent.setGeometry(QtCore.QRect(222, 134, 80, 22))
        self.labelEdit_RightCurrent.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_RightCurrent.setText("")
        self.labelEdit_RightCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_RightCurrent.setObjectName("labelEdit_RightCurrent")
        self.labelEdit_LiftupCurrent = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_LiftupCurrent.setGeometry(QtCore.QRect(222, 188, 80, 22))
        self.labelEdit_LiftupCurrent.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LiftupCurrent.setText("")
        self.labelEdit_LiftupCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LiftupCurrent.setObjectName("labelEdit_LiftupCurrent")
        self.label_205 = QtWidgets.QLabel(self.groupBox_6)
        self.label_205.setGeometry(QtCore.QRect(14, 190, 48, 16))
        self.label_205.setObjectName("label_205")
        self.labelEdit_MotionStatus = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_MotionStatus.setGeometry(QtCore.QRect(374, 162, 80, 22))
        self.labelEdit_MotionStatus.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_MotionStatus.setText("")
        self.labelEdit_MotionStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_MotionStatus.setObjectName("labelEdit_MotionStatus")
        self.labelEdit_Battery_Current = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_Battery_Current.setGeometry(QtCore.QRect(66, 188, 80, 22))
        self.labelEdit_Battery_Current.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Battery_Current.setText("")
        self.labelEdit_Battery_Current.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Battery_Current.setObjectName("labelEdit_Battery_Current")
        self.labelEdit_NavigationMode = QtWidgets.QLabel(self.groupBox_6)
        self.labelEdit_NavigationMode.setGeometry(QtCore.QRect(374, 188, 80, 22))
        self.labelEdit_NavigationMode.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_NavigationMode.setText("")
        self.labelEdit_NavigationMode.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_NavigationMode.setObjectName("labelEdit_NavigationMode")
        self.groupBox_DownCameraInformation = QtWidgets.QGroupBox(self.page)
        self.groupBox_DownCameraInformation.setGeometry(QtCore.QRect(0, 304, 459, 100))
        self.groupBox_DownCameraInformation.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}")
        self.groupBox_DownCameraInformation.setObjectName("groupBox_DownCameraInformation")
        self.labelEdit_642_H = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_642_H.setGeometry(QtCore.QRect(66, 70, 80, 22))
        self.labelEdit_642_H.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_642_H.setText("")
        self.labelEdit_642_H.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_642_H.setObjectName("labelEdit_642_H")
        self.labelEdit_642_X = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_642_X.setGeometry(QtCore.QRect(66, 18, 80, 22))
        self.labelEdit_642_X.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_642_X.setText("")
        self.labelEdit_642_X.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_642_X.setObjectName("labelEdit_642_X")
        self.labelEdit_642_Y = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_642_Y.setGeometry(QtCore.QRect(66, 44, 80, 22))
        self.labelEdit_642_Y.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_642_Y.setText("")
        self.labelEdit_642_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_642_Y.setObjectName("labelEdit_642_Y")
        self.labelEdit_Last_X = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_Last_X.setGeometry(QtCore.QRect(222, 18, 80, 22))
        self.labelEdit_Last_X.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Last_X.setText("")
        self.labelEdit_Last_X.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Last_X.setObjectName("labelEdit_Last_X")
        self.labelEdit_Last_Y = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_Last_Y.setGeometry(QtCore.QRect(222, 44, 80, 22))
        self.labelEdit_Last_Y.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Last_Y.setText("")
        self.labelEdit_Last_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Last_Y.setObjectName("labelEdit_Last_Y")
        self.labelEdit_DeltaX = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_DeltaX.setGeometry(QtCore.QRect(374, 18, 80, 22))
        self.labelEdit_DeltaX.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DeltaX.setText("")
        self.labelEdit_DeltaX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DeltaX.setObjectName("labelEdit_DeltaX")
        self.labelEdit_DeltaY = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_DeltaY.setGeometry(QtCore.QRect(374, 44, 80, 22))
        self.labelEdit_DeltaY.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DeltaY.setText("")
        self.labelEdit_DeltaY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DeltaY.setObjectName("labelEdit_DeltaY")
        self.labelEdit_DeltaH = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.labelEdit_DeltaH.setGeometry(QtCore.QRect(222, 70, 80, 22))
        self.labelEdit_DeltaH.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DeltaH.setText("")
        self.labelEdit_DeltaH.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DeltaH.setObjectName("labelEdit_DeltaH")
        self.label_63 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_63.setGeometry(QtCore.QRect(5, 68, 68, 20))
        self.label_63.setMinimumSize(QtCore.QSize(68, 20))
        self.label_63.setMaximumSize(QtCore.QSize(68, 20))
        self.label_63.setObjectName("label_63")
        self.label_80 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_80.setGeometry(QtCore.QRect(5, 18, 68, 20))
        self.label_80.setMinimumSize(QtCore.QSize(68, 20))
        self.label_80.setMaximumSize(QtCore.QSize(68, 20))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_81.setGeometry(QtCore.QRect(5, 43, 68, 20))
        self.label_81.setMinimumSize(QtCore.QSize(68, 20))
        self.label_81.setMaximumSize(QtCore.QSize(68, 20))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_82.setGeometry(QtCore.QRect(161, 18, 68, 20))
        self.label_82.setMinimumSize(QtCore.QSize(68, 20))
        self.label_82.setMaximumSize(QtCore.QSize(68, 20))
        self.label_82.setObjectName("label_82")
        self.label_LastY = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_LastY.setGeometry(QtCore.QRect(161, 43, 68, 20))
        self.label_LastY.setMinimumSize(QtCore.QSize(68, 20))
        self.label_LastY.setMaximumSize(QtCore.QSize(68, 20))
        self.label_LastY.setObjectName("label_LastY")
        self.label_84 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_84.setGeometry(QtCore.QRect(322, 18, 68, 20))
        self.label_84.setMinimumSize(QtCore.QSize(68, 20))
        self.label_84.setMaximumSize(QtCore.QSize(68, 20))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_85.setGeometry(QtCore.QRect(322, 43, 68, 20))
        self.label_85.setMinimumSize(QtCore.QSize(68, 20))
        self.label_85.setMaximumSize(QtCore.QSize(68, 20))
        self.label_85.setObjectName("label_85")
        self.label_DeltaH = QtWidgets.QLabel(self.groupBox_DownCameraInformation)
        self.label_DeltaH.setGeometry(QtCore.QRect(161, 68, 68, 20))
        self.label_DeltaH.setMinimumSize(QtCore.QSize(68, 20))
        self.label_DeltaH.setMaximumSize(QtCore.QSize(68, 20))
        self.label_DeltaH.setObjectName("label_DeltaH")
        self.label_63.raise_()
        self.label_80.raise_()
        self.label_81.raise_()
        self.label_82.raise_()
        self.label_LastY.raise_()
        self.label_84.raise_()
        self.label_85.raise_()
        self.label_DeltaH.raise_()
        self.labelEdit_642_X.raise_()
        self.labelEdit_642_Y.raise_()
        self.labelEdit_Last_X.raise_()
        self.labelEdit_Last_Y.raise_()
        self.labelEdit_DeltaX.raise_()
        self.labelEdit_DeltaY.raise_()
        self.labelEdit_DeltaH.raise_()
        self.labelEdit_642_H.raise_()
        self.groupBox_UpCameraInformation = QtWidgets.QGroupBox(self.page)
        self.groupBox_UpCameraInformation.setGeometry(QtCore.QRect(0, 410, 459, 73))
        self.groupBox_UpCameraInformation.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}")
        self.groupBox_UpCameraInformation.setObjectName("groupBox_UpCameraInformation")
        self.label_87 = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.label_87.setGeometry(QtCore.QRect(5, 16, 68, 20))
        self.label_87.setMinimumSize(QtCore.QSize(68, 20))
        self.label_87.setMaximumSize(QtCore.QSize(68, 20))
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.label_88.setGeometry(QtCore.QRect(161, 40, 68, 20))
        self.label_88.setMinimumSize(QtCore.QSize(68, 20))
        self.label_88.setMaximumSize(QtCore.QSize(68, 20))
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.label_89.setGeometry(QtCore.QRect(161, 16, 68, 20))
        self.label_89.setMinimumSize(QtCore.QSize(68, 20))
        self.label_89.setMaximumSize(QtCore.QSize(68, 20))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.label_90.setGeometry(QtCore.QRect(322, 16, 68, 20))
        self.label_90.setMinimumSize(QtCore.QSize(68, 20))
        self.label_90.setMaximumSize(QtCore.QSize(68, 20))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.label_91.setGeometry(QtCore.QRect(5, 41, 68, 20))
        self.label_91.setMinimumSize(QtCore.QSize(68, 20))
        self.label_91.setMaximumSize(QtCore.QSize(68, 20))
        self.label_91.setObjectName("label_91")
        self.labelEdit_ShelfNumber = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.labelEdit_ShelfNumber.setGeometry(QtCore.QRect(66, 16, 80, 22))
        self.labelEdit_ShelfNumber.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_ShelfNumber.setText("")
        self.labelEdit_ShelfNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_ShelfNumber.setObjectName("labelEdit_ShelfNumber")
        self.labelEdit_Shelf_X = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.labelEdit_Shelf_X.setGeometry(QtCore.QRect(222, 42, 80, 22))
        self.labelEdit_Shelf_X.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Shelf_X.setText("")
        self.labelEdit_Shelf_X.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Shelf_X.setObjectName("labelEdit_Shelf_X")
        self.labelEdit_Shelf_Y = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.labelEdit_Shelf_Y.setGeometry(QtCore.QRect(222, 16, 80, 22))
        self.labelEdit_Shelf_Y.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Shelf_Y.setText("")
        self.labelEdit_Shelf_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Shelf_Y.setObjectName("labelEdit_Shelf_Y")
        self.labelEdit_Shelf_H = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.labelEdit_Shelf_H.setGeometry(QtCore.QRect(374, 16, 80, 22))
        self.labelEdit_Shelf_H.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_Shelf_H.setText("")
        self.labelEdit_Shelf_H.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_Shelf_H.setObjectName("labelEdit_Shelf_H")
        self.labelEdit_ShelfFace = QtWidgets.QLabel(self.groupBox_UpCameraInformation)
        self.labelEdit_ShelfFace.setGeometry(QtCore.QRect(66, 42, 80, 22))
        self.labelEdit_ShelfFace.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_ShelfFace.setText("")
        self.labelEdit_ShelfFace.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_ShelfFace.setObjectName("labelEdit_ShelfFace")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 5, 458, 69))
        self.groupBox_8.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}\n"
"QLabel {\n"
"  background: rgb(82, 82, 82);\n"
"\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_Command_Mode = QtWidgets.QLabel(self.groupBox_8)
        self.label_Command_Mode.setGeometry(QtCore.QRect(248, 40, 129, 20))
        self.label_Command_Mode.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);\n"
"")
        self.label_Command_Mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Command_Mode.setObjectName("label_Command_Mode")
        self.label_salver = QtWidgets.QLabel(self.groupBox_8)
        self.label_salver.setGeometry(QtCore.QRect(142, 40, 100, 20))
        self.label_salver.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_salver.setAlignment(QtCore.Qt.AlignCenter)
        self.label_salver.setObjectName("label_salver")
        self.label_gyroscope = QtWidgets.QLabel(self.groupBox_8)
        self.label_gyroscope.setGeometry(QtCore.QRect(6, 40, 128, 20))
        self.label_gyroscope.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_gyroscope.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gyroscope.setObjectName("label_gyroscope")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(326, 16, 50, 20))
        self.label_13.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_shelves = QtWidgets.QLabel(self.groupBox_8)
        self.label_shelves.setGeometry(QtCore.QRect(61, 16, 60, 20))
        self.label_shelves.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_shelves.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shelves.setObjectName("label_shelves")
        self.label_Motor_switch = QtWidgets.QLabel(self.groupBox_8)
        self.label_Motor_switch.setGeometry(QtCore.QRect(131, 16, 60, 20))
        self.label_Motor_switch.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_Motor_switch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Motor_switch.setObjectName("label_Motor_switch")
        self.label_code = QtWidgets.QLabel(self.groupBox_8)
        self.label_code.setGeometry(QtCore.QRect(6, 16, 51, 20))
        self.label_code.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_code.setAlignment(QtCore.Qt.AlignCenter)
        self.label_code.setObjectName("label_code")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(206, 16, 60, 20))
        self.label_17.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(272, 16, 50, 20))
        self.label_18.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(380, 40, 60, 20))
        self.label_11.setStyleSheet("border: 1px solid rgb(36, 36, 36); ")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_AGV_PodSensor = QtWidgets.QLabel(self.groupBox_8)
        self.label_AGV_PodSensor.setGeometry(QtCore.QRect(380, 16, 60, 20))
        self.label_AGV_PodSensor.setStyleSheet("border: 1px solid rgb(36, 36, 36);")
        self.label_AGV_PodSensor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AGV_PodSensor.setObjectName("label_AGV_PodSensor")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 460, 485))
        self.page_2.setObjectName("page_2")
        self.groupBox_SoftwareVersion = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_SoftwareVersion.setGeometry(QtCore.QRect(1, 5, 224, 126))
        self.groupBox_SoftwareVersion.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}")
        self.groupBox_SoftwareVersion.setObjectName("groupBox_SoftwareVersion")
        self.label_101 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.label_101.setGeometry(QtCore.QRect(10, 24, 68, 20))
        self.label_101.setMinimumSize(QtCore.QSize(68, 20))
        self.label_101.setMaximumSize(QtCore.QSize(68, 20))
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.label_102.setEnabled(True)
        self.label_102.setGeometry(QtCore.QRect(10, 48, 68, 20))
        self.label_102.setMinimumSize(QtCore.QSize(68, 20))
        self.label_102.setMaximumSize(QtCore.QSize(68, 20))
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.label_103.setGeometry(QtCore.QRect(10, 74, 68, 20))
        self.label_103.setMinimumSize(QtCore.QSize(68, 20))
        self.label_103.setMaximumSize(QtCore.QSize(68, 20))
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.label_104.setGeometry(QtCore.QRect(10, 98, 68, 20))
        self.label_104.setMinimumSize(QtCore.QSize(68, 20))
        self.label_104.setMaximumSize(QtCore.QSize(68, 20))
        self.label_104.setObjectName("label_104")
        self.labelEdit_DSP = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.labelEdit_DSP.setGeometry(QtCore.QRect(80, 24, 125, 20))
        self.labelEdit_DSP.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_DSP.setText("")
        self.labelEdit_DSP.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_DSP.setObjectName("labelEdit_DSP")
        self.labelEdit_STM32 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.labelEdit_STM32.setGeometry(QtCore.QRect(80, 48, 125, 20))
        self.labelEdit_STM32.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_STM32.setText("")
        self.labelEdit_STM32.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_STM32.setObjectName("labelEdit_STM32")
        self.labelEdit_laser = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.labelEdit_laser.setGeometry(QtCore.QRect(80, 74, 125, 20))
        self.labelEdit_laser.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_laser.setText("")
        self.labelEdit_laser.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_laser.setObjectName("labelEdit_laser")
        self.labelEdit_642 = QtWidgets.QLabel(self.groupBox_SoftwareVersion)
        self.labelEdit_642.setGeometry(QtCore.QRect(80, 98, 125, 20))
        self.labelEdit_642.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_642.setText("")
        self.labelEdit_642.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_642.setObjectName("labelEdit_642")
        self.groupBox_Mileage_information = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_Mileage_information.setGeometry(QtCore.QRect(234, 3, 224, 129))
        self.groupBox_Mileage_information.setStyleSheet("QGroupBox {\n"
"  border: 1.5px solid rgb(36, 36, 36);\n"
"}\n"
"")
        self.groupBox_Mileage_information.setObjectName("groupBox_Mileage_information")
        self.label_105 = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.label_105.setGeometry(QtCore.QRect(16, 24, 68, 20))
        self.label_105.setMinimumSize(QtCore.QSize(68, 20))
        self.label_105.setMaximumSize(QtCore.QSize(68, 20))
        self.label_105.setObjectName("label_105")
        self.label_108 = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.label_108.setGeometry(QtCore.QRect(14, 98, 68, 20))
        self.label_108.setMinimumSize(QtCore.QSize(68, 20))
        self.label_108.setMaximumSize(QtCore.QSize(68, 20))
        self.label_108.setObjectName("label_108")
        self.label_107 = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.label_107.setGeometry(QtCore.QRect(17, 74, 68, 20))
        self.label_107.setMinimumSize(QtCore.QSize(68, 20))
        self.label_107.setMaximumSize(QtCore.QSize(68, 20))
        self.label_107.setObjectName("label_107")
        self.label_106 = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.label_106.setEnabled(True)
        self.label_106.setGeometry(QtCore.QRect(17, 48, 68, 20))
        self.label_106.setMinimumSize(QtCore.QSize(68, 20))
        self.label_106.setMaximumSize(QtCore.QSize(68, 20))
        self.label_106.setObjectName("label_106")
        self.labelEdit_No_Load_Mileage = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.labelEdit_No_Load_Mileage.setGeometry(QtCore.QRect(74, 24, 125, 20))
        self.labelEdit_No_Load_Mileage.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_No_Load_Mileage.setText("")
        self.labelEdit_No_Load_Mileage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_No_Load_Mileage.setObjectName("labelEdit_No_Load_Mileage")
        self.labelEdit_On_Load_Mileage = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.labelEdit_On_Load_Mileage.setGeometry(QtCore.QRect(74, 48, 125, 20))
        self.labelEdit_On_Load_Mileage.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_On_Load_Mileage.setText("")
        self.labelEdit_On_Load_Mileage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_On_Load_Mileage.setObjectName("labelEdit_On_Load_Mileage")
        self.labelEdit_mileage = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.labelEdit_mileage.setGeometry(QtCore.QRect(74, 74, 125, 20))
        self.labelEdit_mileage.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_mileage.setText("")
        self.labelEdit_mileage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_mileage.setObjectName("labelEdit_mileage")
        self.labelEdit_LiftupCount = QtWidgets.QLabel(self.groupBox_Mileage_information)
        self.labelEdit_LiftupCount.setGeometry(QtCore.QRect(74, 98, 125, 20))
        self.labelEdit_LiftupCount.setStyleSheet("border: 1px solid rgb(36, 36, 36);        background: rgb(82, 82, 82);")
        self.labelEdit_LiftupCount.setText("")
        self.labelEdit_LiftupCount.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEdit_LiftupCount.setObjectName("labelEdit_LiftupCount")
        self.toolBox.addItem(self.page_2, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.textEdit_data_show = QtWidgets.QTextEdit(self.tab_8)
        self.textEdit_data_show.setGeometry(QtCore.QRect(1, 5, 795, 560))
        self.textEdit_data_show.setStyleSheet("color: rgb(0, 78, 161);background-color: rgb(255, 255, 255);")
        self.textEdit_data_show.setObjectName("textEdit_data_show")
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.pushButton_Clear.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "循环次数"))
        self.comboBox.setItemText(1, _translate("MainWindow", "移动"))
        self.comboBox.setItemText(2, _translate("MainWindow", "旋转"))
        self.comboBox.setItemText(3, _translate("MainWindow", "顶升"))
        self.comboBox.setItemText(4, _translate("MainWindow", "下降"))
        self.comboBox.setItemText(5, _translate("MainWindow", "充电"))
        self.comboBox.setItemText(6, _translate("MainWindow", "退出充电"))
        self.comboBox.setItemText(7, _translate("MainWindow", "设置托盘高度"))
        self.comboBox.setItemText(8, _translate("MainWindow", "顶升前确认"))
        self.comboBox.setItemText(9, _translate("MainWindow", "顶升后确认"))
        self.comboBox.setItemText(10, _translate("MainWindow", "托盘碰限位"))
        self.comboBox.setItemText(11, _translate("MainWindow", "托盘归零"))
        self.comboBox.setItemText(12, _translate("MainWindow", "陀螺仪归零"))
        self.comboBox.setItemText(13, _translate("MainWindow", "重启642"))
        self.comboBox.setItemText(14, _translate("MainWindow", "一键启动"))
        self.comboBox.setItemText(15, _translate("MainWindow", "查询电量"))
        self.comboBox.setItemText(16, _translate("MainWindow", "重置"))
        self.comboBox.setItemText(17, _translate("MainWindow", "微移动"))
        self.comboBox.setItemText(18, _translate("MainWindow", "微转向"))
        self.comboBox.setItemText(19, _translate("MainWindow", "DeBug"))
        self.comboBox.setItemText(20, _translate("MainWindow", "货架换向"))
        self.comboBox.setItemText(21, _translate("MainWindow", "获得下位机里程"))
        self.comboBox.setItemText(22, _translate("MainWindow", "获得下位机版本号"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "基本操作"))
        self.pushButton_Suspend.setText(_translate("MainWindow", "暂停"))
        self.pushButton_Run.setText(_translate("MainWindow", "运行"))
        self.pushButton_Stop.setText(_translate("MainWindow", "停止"))
        self.pushButton_Add_Cmd.setText(_translate("MainWindow", "Add"))
        self.pushButton_Clear.setText(_translate("MainWindow", "清除"))
        self.groupBox_6.setTitle(_translate("MainWindow", "DSP反馈面板"))
        self.label_58.setText(_translate("MainWindow", "左右负载差"))
        self.label_52.setText(_translate("MainWindow", "车辆速度"))
        self.label_56.setText(_translate("MainWindow", "障碍距离"))
        self.label_48.setText(_translate("MainWindow", "反馈Y坐标"))
        self.label_201.setText(_translate("MainWindow", "当前指令"))
        self.label_96.setText(_translate("MainWindow", "电池电量"))
        self.label_47.setText(_translate("MainWindow", "反馈X坐标"))
        self.label_51.setText(_translate("MainWindow", "反馈角度"))
        self.label_55.setText(_translate("MainWindow", "托盘角度"))
        self.label_57.setText(_translate("MainWindow", "托盘高度"))
        self.label_95.setText(_translate("MainWindow", "电池电压"))
        self.label_198.setText(_translate("MainWindow", "运动状态"))
        self.label_200.setText(_translate("MainWindow", "导航模式"))
        self.label_49.setText(_translate("MainWindow", "左侧负载率"))
        self.label_53.setText(_translate("MainWindow", "右侧负载率"))
        self.label_59.setText(_translate("MainWindow", "顶升负载率"))
        self.label_61.setText(_translate("MainWindow", "左右负载差"))
        self.label_202.setText(_translate("MainWindow", "左侧电流"))
        self.label_203.setText(_translate("MainWindow", "右侧电流"))
        self.label_204.setText(_translate("MainWindow", "顶升电流"))
        self.label_205.setText(_translate("MainWindow", "放电电流"))
        self.groupBox_DownCameraInformation.setTitle(_translate("MainWindow", "下视摄像头反馈"))
        self.label_63.setText(_translate("MainWindow", "角度"))
        self.label_80.setText(_translate("MainWindow", "反馈X坐标"))
        self.label_81.setText(_translate("MainWindow", "反馈Y坐标"))
        self.label_82.setText(_translate("MainWindow", "上次X坐标"))
        self.label_LastY.setText(_translate("MainWindow", "上次Y坐标"))
        self.label_84.setText(_translate("MainWindow", "DeltaX"))
        self.label_85.setText(_translate("MainWindow", "DeltaY"))
        self.label_DeltaH.setText(_translate("MainWindow", "DeltaH"))
        self.groupBox_UpCameraInformation.setTitle(_translate("MainWindow", "上视摄像头反馈"))
        self.label_87.setText(_translate("MainWindow", "货架号"))
        self.label_88.setText(_translate("MainWindow", "反馈X坐标"))
        self.label_89.setText(_translate("MainWindow", "反馈Y坐标"))
        self.label_90.setText(_translate("MainWindow", "货架角度"))
        self.label_91.setText(_translate("MainWindow", "货位面"))
        self.groupBox_8.setTitle(_translate("MainWindow", "信号面板"))
        self.label_Command_Mode.setText(_translate("MainWindow", "命令执行完成"))
        self.label_salver.setText(_translate("MainWindow", "托盘限位未确认"))
        self.label_gyroscope.setText(_translate("MainWindow", "陀螺仪零偏纠正未完成"))
        self.label_13.setText(_translate("MainWindow", "正常帧"))
        self.label_shelves.setText(_translate("MainWindow", "载有货架"))
        self.label_Motor_switch.setText(_translate("MainWindow", "电机开启"))
        self.label_code.setText(_translate("MainWindow", "在码上"))
        self.label_17.setText(_translate("MainWindow", "货架正常"))
        self.label_18.setText(_translate("MainWindow", "未休眠"))
        self.label_11.setText(_translate("MainWindow", "捕获异常"))
        self.label_AGV_PodSensor.setText(_translate("MainWindow", "电池状态"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "基础信息"))
        self.groupBox_SoftwareVersion.setTitle(_translate("MainWindow", "下位机软件版本号"))
        self.label_101.setText(_translate("MainWindow", "DSP版本号"))
        self.label_102.setText(_translate("MainWindow", "STM32版本号："))
        self.label_103.setText(_translate("MainWindow", "激光雷达"))
        self.label_104.setText(_translate("MainWindow", "摄像头"))
        self.groupBox_Mileage_information.setTitle(_translate("MainWindow", "里程信息"))
        self.label_105.setText(_translate("MainWindow", "空载里程"))
        self.label_108.setText(_translate("MainWindow", "顶升次数"))
        self.label_107.setText(_translate("MainWindow", "总里程"))
        self.label_106.setText(_translate("MainWindow", "带载里程"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "版本信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "车辆控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "原始数据"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

