# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\驱动器参数校验\子函数模块\HlsBk驱动器参数校验程序X4\down_list.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(613, 576)
        Dialog.setSizeGripEnabled(True)
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(520, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.pushButton_close.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/cleck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon)
        self.pushButton_close.setObjectName("pushButton_close")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(210, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setScaledContents(True)
        self.label2.setObjectName("label2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_province = QtWidgets.QComboBox(Dialog)
        self.comboBox_province.setGeometry(QtCore.QRect(90, 70, 61, 22))
        self.comboBox_province.setObjectName("comboBox_province")
        self.comboBox_city = QtWidgets.QComboBox(Dialog)
        self.comboBox_city.setGeometry(QtCore.QRect(260, 70, 61, 21))
        self.comboBox_city.setObjectName("comboBox_city")
        self.comboBox_town = QtWidgets.QComboBox(Dialog)
        self.comboBox_town.setGeometry(QtCore.QRect(440, 70, 61, 22))
        self.comboBox_town.setObjectName("comboBox_town")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(170, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(340, 70, 91, 20))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(350, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.pushButton_ok.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/run2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ok.setIcon(icon1)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.lblResult = QtWidgets.QLabel(Dialog)
        self.lblResult.setGeometry(QtCore.QRect(100, 110, 291, 16))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 140, 571, 391))
        self.textEdit.setObjectName("textEdit")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 540, 331, 23))
        self.progressBar.setMaximum(512)
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")
        self.label_log2 = QtWidgets.QLabel(Dialog)
        self.label_log2.setGeometry(QtCore.QRect(0, 0, 91, 71))
        self.label_log2.setText("")
        self.label_log2.setPixmap(QtGui.QPixmap(":/pic/lg3jpg.jpg"))
        self.label_log2.setScaledContents(True)
        self.label_log2.setObjectName("label_log2")
        self.pushButton_study = QtWidgets.QPushButton(Dialog)
        self.pushButton_study.setGeometry(QtCore.QRect(440, 540, 75, 23))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.pushButton_study.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("study2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_study.setIcon(icon2)
        self.pushButton_study.setObjectName("pushButton_study")

        self.retranslateUi(Dialog)
        self.pushButton_close.clicked.connect(self.textEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_close.setText(_translate("Dialog", "清除"))
        self.label2.setText(_translate("Dialog", "驱动器参数对比软件"))
        self.label_7.setText(_translate("Dialog", "串口号"))
        self.label_34.setText(_translate("Dialog", "驱动器类型："))
        self.label_4.setText(_translate("Dialog", "驱动器站号："))
        self.label_5.setText(_translate("Dialog", "选择结果："))
        self.pushButton_ok.setText(_translate("Dialog", "开始"))
        self.lblResult.setText(_translate("Dialog", "（未选择）"))
        self.pushButton_study.setText(_translate("Dialog", "学习"))

import apprcc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

